### ISSUE TITLE
Add WordPress

### ISSUE THREAD

**Issue by furzeface** [furzeface/super-button#12]
One for @fephil.

**Comment by fephil** [comment]
What is this?

**Comment by furzeface** [comment]
We're going to need to content manage the button. Can you hook WordPress into Elastic, CouchDB and PouchDB? Thanks.

**Comment by furzeface** [comment]
Maybe we should consider Umbraco as a service @antplant or perhaps Tridion?

**Comment by antplant** [comment]
We will need Tridion for future-proofing wrt localization.
